trigger:
    batch: false
    branches:
        include:
            - dev
            - master

pool:
    name: ubuntu-22.04
    demands: java

variables:
    enableCodeScanning: 'true'

resources:
    repositories:
        - repository: templates
          type: git
          name: Platform/templates

workspace:
    clean: all

steps:
    - template: GitVersion.yml@templates
      parameters:
          useDotnet: true

    - task: NodeTool@0
      inputs:
          versionSpec: '18.x'
      displayName: 'Install Node.js'

    - task: replacetokens@5
      displayName: 'Update SonarQube Settings'
      inputs:
          targetFiles: '**/*sonar.ts'
          encoding: 'auto'
          tokenPattern: 'default'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          actionOnNoFiles: 'continue'
          enableTransforms: false
          enableRecursion: false
          useLegacyPattern: false
          enableTelemetry: true

    - script: |
          cd '$(System.DefaultWorkingDirectory)/'
          corepack enable
          corepack prepare pnpm@latest-9 --activate
          pnpm config set store-dir $(Pipeline.Workspace)/.pnpm-store
          pnpm install
          pnpm run build
      displayName: 'npm install and build'

    - script: |
          cd '$(System.DefaultWorkingDirectory)/'
          pnpm run sonar
      displayName: 'Run Code Analysis'
      condition: and(succeeded(), eq('${{ variables.enableCodeScanning }}', 'true'))

    - task: ArchiveFiles@2
      inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/storybook-static'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/Portal.zip'
          replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/Portal.zip'
          ArtifactName: 'drop'
          publishLocation: 'Container'
