/* eslint-disable @typescript-eslint/no-var-requires */
/** @type {import('tailwindcss').Config} */
const plugin = require('tailwindcss/plugin')
const { dgaToken } = require('./dga.config')
module.exports = {
    darkMode: ['class'],
    content: ['./pages/**/*.{ts,tsx}', './components/**/*.{ts,tsx,mdx}', './app/**/*.{ts,tsx}', './src/**/*.{ts,tsx,mdx}'],
    theme: {
        container: {
            center: true,
            padding: {
                DEFAULT: '1.6rem',
                sm: '1.6rem',
                md: '3.2rem',
                lg: '3.2rem',
                xl: '6.4rem',
                '2xl': '6.4rem',
            },
            screens: {
                DEFAULT: '100%',
                sm: '100%',
                md: '100%',
                lg: '100%',
                xl: '100%',
                '2xl': '1592px',
            },
        },

        extend: {
            backgroundImage: theme => ({
                gradientPrimary: `linear-gradient(0deg, ${theme('colors.primary.dark')} 0%, ${theme('colors.primary.DEFAULT')} 100%)`,
                HeaderGradient: `linear-gradient(180deg, ${theme('colors.primary.container')} -15%, ${theme('colors.card.DEFAULT')} 80%)`,
            }),
            colors: {
                foreground: {
                    DEFAULT: 'var(--foreground)',
                    secondary: 'var(--foreground-secondary)',
                    tertiary: 'var(--foreground-tertiary)',
                },
                disabled: {
                    DEFAULT: 'var(--disabled)',
                    secondary: 'var(--disabled-foreground)',
                },
                primary: {
                    DEFAULT: 'var(--primary)',
                    foreground: 'var(--primary-foreground)',
                    light: 'var(--primary-light)',
                    dark: 'var(--primary-dark)',
                    oncontainer: 'var(--primary-oncontainer)',
                    container: 'var(--primary-container)',
                },
                secondary: {
                    DEFAULT: 'var(--secondary)',
                    foreground: 'var(--secondary-foreground)',
                    light: 'var(--secondary-light)',
                    dark: 'var(--secondary-dark)',
                    oncontainer: 'var(--secondary-oncontainer)',
                    container: 'var(--secondary-container)',
                },
                tertiary: {
                    DEFAULT: 'var(--tertiary)',
                    foreground: 'var(--tertiary-foreground)',
                    light: 'var(--tertiary-light)',
                    dark: 'var(--tertiary-dark)',
                    oncontainer: 'var(--tertiary-oncontainer)',
                    container: 'var(--tertiary-container)',
                },
                success: {
                    DEFAULT: 'var(--sucess)',
                    foreground: 'var(--sucess-foreground)',
                    light: 'var(--sucess-light)',
                    dark: 'var(--sucess-dark)',
                    oncontainer: 'var(--sucess-oncontainer)',
                    container: 'var(--sucess-container)',
                },
                error: {
                    DEFAULT: 'var(--error)',
                    foreground: 'var(--error-foreground)',
                    light: 'var(--error-light)',
                    dark: 'var(--error-dark)',
                    oncontainer: 'var(--error-oncontainer)',
                    container: 'var(--error-container)',
                },
                warning: {
                    DEFAULT: 'var(--warning)',
                    foreground: 'var(--warning-foreground)',
                    light: 'var(--warning-light)',
                    dark: 'var(--warning-dark)',
                    oncontainer: 'var(--warning-oncontainer)',
                    container: 'var(--warning-container)',
                },
                info: {
                    DEFAULT: 'var(--info)',
                    foreground: 'var(--info-foreground)',
                    light: 'var(--info-light)',
                    dark: 'var(--info-dark)',
                    oncontainer: 'var(--info-oncontainer)',
                    container: 'var(--info-container)',
                },
                destructive: {
                    DEFAULT: 'var(--destructive)',
                    foreground: 'var(--destructive-foreground)',
                },
                muted: {
                    DEFAULT: 'var(--muted)',
                    foreground: 'var(--muted-foreground)',
                },
                accent: {
                    DEFAULT: 'hsl(var(--accent))',
                    foreground: 'hsl(var(--accent-foreground))',
                },
                popover: {
                    DEFAULT: 'var(--popover)',
                    foreground: 'var(--popover-foreground)',
                },
                card: {
                    DEFAULT: 'var(--card)',
                    foreground: 'var(--card-foreground)',
                    hover: 'var(--card-hover)',
                    active: 'var(--card-active)',
                },
                inverted: {
                    DEFAULT: 'var(--inverted)',
                    secondary: 'var(--inverted-foreground)',
                    foreground: 'var(--inverted-foreground)',
                },
                skeleton: {
                    DEFAULT: 'var(--skeleton)',
                },
                divider: {
                    DEFAULT: 'var(--divider)',
                },
                input: 'var(--input)',
                ring: 'hsl(var(--ring))',

                ...dgaToken,

                gray: {
                    50: '#FAFAFA',
                    100: '#F9f9f9',
                    200: '#7E7E7E0D',
                    300: '#EBEBEB',
                    400: '#353B3A33',
                    500: '#353B3A3B',
                    600: '#393A404D',
                    700: '#353B3A99',
                    800: '#212625BD',
                    900: '#0F0F0F',
                },
                grayDark: {
                    10: '#FFFFFF',
                    50: '#CECECE',
                    100: '#B7BBBC',
                    200: '#8F9395',
                    300: '#7F8B91',
                    400: '#636F77',
                    500: '#555E65',
                    600: '#494F55',
                    700: '#414549',
                    800: '#313336',
                    900: '#242629',
                },
                neutral: {
                    10: '#FFFFFF',
                    25: '#FCFCFD',
                    50: '#F9FAFB',
                    100: '#F3F4F',
                    200: '#E5E7E',
                    300: '#D2D6D',
                    400: '#9DA4A',
                    500: '#6C737',
                    600: '#4D576',
                    700: '#38425',
                    800: '#1F2A3',
                    900: '#11192',
                    950: '#0D12',
                },
                lavender: {
                    10: '#FFFFFF',
                    25: '#FEFCFF',
                    50: '#F9F5FA',
                    100: '#F2E9F',
                    200: '#E1CCE',
                    300: '#CCADD',
                    400: '#A57BB',
                    500: '#80519',
                    600: '#6D428',
                    700: '#532D7',
                    800: '#3D1D5',
                    900: '#28104',
                    950: '#16072',
                },
                middleBlue: {
                    10: '#FFFFFF',
                    25: '#F8FBFC',
                    50: '#F3FAFC',
                    100: '#E2F6FC',
                    200: '#D1EFF8',
                    300: '#BEE6F3',
                    400: '#BEE6F3',
                    500: '#5DB5CE',
                    600: '#038BA7',
                    700: '#007E99',
                    800: '#007B97',
                    900: '#173D47',
                },
                blue: {
                    10: '#FFFFFF',
                    25: '#F5FAFF',
                    50: '#EFF8FF',
                    100: '#D1E9F',
                    200: '#B2DDF',
                    300: '#84CAF',
                    400: '#53B1F',
                    500: '#2E90F',
                    600: '#1570E',
                    700: '#175CD',
                    800: '#1849A',
                    900: '#19418',
                    950: '#102A5',
                },
                green: {
                    10: '#FFFFFF',
                    25: '#F6FEF9',
                    50: '#ECFDF3',
                    100: '#DCFAE',
                    200: '#ABEFC',
                    300: '#75E0A',
                    400: '#47CD8',
                    500: '#17B26',
                    600: '#07945',
                    700: '#06764',
                    800: '#085D3',
                    900: '#074D3',
                    950: '#05332',
                },
                red: {
                    10: '#FFFFFF',
                    25: '#FFFBFA',
                    50: '#FEF3F2',
                    100: ' #FEE4E',
                    200: ' #FECDC',
                    300: ' #FDA29',
                    400: ' #F9706',
                    500: ' #F0443',
                    600: ' #D92D2',
                    700: ' #B4231',
                    800: ' #91201',
                    900: ' #7A271',
                    950: ' #55160',
                },
                olivine: {
                    10: '#FFFFFF',
                    50: '#F5F9EC',
                    100: '#E8F2D5',
                    200: '#D4E6B0',
                    300: '#B8D482',
                    400: '#A2C566',
                    500: '#7CA63C',
                    600: '#61832D',
                    700: '#4B6526',
                    800: '#3D5123',
                    900: '#344720',
                },
                puertoRico: {
                    10: '#FFFFFF',
                    50: '#F2FBF9',
                    100: '#D2F5ED',
                    200: '#A4EBDB',
                    300: '#6FD8C7',
                    400: '#4AC3B1',
                    500: '#28A594',
                    600: '#1D8479',
                    700: '#1B6A62',
                    800: '#1B6A62',
                    900: '#194743',
                },
                marigold: {
                    10: '#FFFFFF',
                    25: '#FFFCF5',
                    50: '#FFFAEB',
                    100: '#FEF0C',
                    200: '#FEDF8',
                    300: '#FEC84',
                    400: '#FDB02',
                    500: '#F7900',
                    600: '#DC680',
                    700: '#B5470',
                    800: '#93370',
                    900: '#7A2E0',
                    950: '#4E1D0',
                },
                gold: {
                    10: '#FFFFFF',
                    25: '#FFFEF7',
                    50: '#FFFEF2',
                    100: '#FFFCE6',
                    200: '#FCF3BD',
                    300: '#FAE996',
                    400: '#F7D54D',
                    500: '#F5BD02',
                    600: '#DBA102',
                    700: '#B87B02',
                    800: '#945C01',
                    900: '#6E3C00',
                    950: '#472400',
                },
                cyan: {
                    10: '#FFFFFF',
                    25: '#F7FDF9',
                    50: '#F3FCF6',
                    100: '#DFF6E7',
                    200: '#B8EACB',
                    300: '#88D8AD',
                    400: '#54C08A',
                    500: '#25935F',
                    600: '#1B8354',
                    700: '#166A45',
                    800: '#14573A',
                    900: '#104631',
                    950: '#092A1E',
                },
                azure: {
                    50: '#EAF3FB',
                    100: '#D9EBF7',
                    200: '#B2D6F0',
                    300: '#8CC1E9',
                    400: '#66AEE1',
                    500: '#2683C4',
                    600: '#2683C4',
                    700: '#20689D',
                    800: '#184F77',
                    900: '#113651',
                },
                alpha: {
                    'white-0': '#FFFFFF00',
                    'black-0': '#16161600',
                    'black-10': '#16161619',
                    'black-20': '#16161633',
                    'black-30': '#1616164C',
                    'black-40': '#16161666',
                    'black-50': '#1616167F',
                    'black-60': '#16161699',
                    'black-70': '#161616B2',
                    'black-80': '#161616CC',
                    'black-90': '#161616E5',
                    'black-100': '#161616',
                    'white-10': '#FFFFFF19',
                    'white-20': '#FFFFFF33',
                    'white-30': '#FFFFFF4C',
                    'white-40': '#FFFFFF66',
                    'white-50': '#FFFFFF7F',
                    'white-60': '#FFFFFF99',
                    'white-70': '#FFFFFFB2',
                    'white-80': '#FFFFFFCC',
                    'white-90': '#FFFFFFE5',
                    'white-100': '#FFFFFF',
                    'cyan-0': '#1B835400',
                    'cyan-10': '#1B835419',
                    'cyan-20': '#1B835433',
                    'cyan-30': '#1B83544C',
                    'cyan-40': '#1B835466',
                    'cyan-50': '#1B83547F',
                    'cyan-60': '#1B835499',
                    'cyan-70': '#1B8354B2',
                    'cyan-80': '#1B8354CC',
                    'cyan-90': '#1B8354E5',
                    //"cyan-100": var(--color-"cyan-600)",
                    'green-10': '#07945519',
                    'green-20': '#07945533',
                    'blue-10': '#1570EF19',
                    'blue-20': '#1570EF33',
                    'red-10': '#D92D2019',
                    'red-20': '#D92D2033',
                    'marigold-10': '#DC680319',
                    'marigold-20': '#DC680333',
                    'Alpha-primary-10': '#1B83541A',
                    'Alpha-primary-20': '#1B835433',
                    'Alpha-warning-10': '#DC68031A',
                    'Alpha-warning-20': '#DC680333',
                    'Alpha-error-10': '#D92D201A',
                    'Alpha-error-20': '#D92D2033',
                    'Alpha-info-10': '#1570EF1A',
                    'Alpha-info-20': '#1570EF33',
                    'Alpha-success-10': '#0794551A',
                    'Alpha-success-20': '#07945533',
                },
            },
            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)',
                1: '8px',
                2: '12px',
                3: '16px',
                4: '24px',
                5: '32px',
                6: '40px',
                7: '48px',
                8: '64px',
            },
            keyframes: {
                'accordion-down': {
                    from: { height: 0 },
                    to: { height: 'var(--radix-accordion-content-height)' },
                },
                'accordion-up': {
                    from: { height: 'var(--radix-accordion-content-height)' },
                    to: { height: 0 },
                },
            },
            animation: {
                'accordion-down': 'accordion-down 0.2s ease-out',
                'accordion-up': 'accordion-up 0.2s ease-out',
            },
            spacing: {
                'space-00': '0px',
                'space-01': '4px',
                'space-02': '8px',
                'space-03': '12px',
                'space-04': '16px',
                'space-05': '24px',
                'space-06': '32px',
                'space-07': '40px',
                'space-08': '48px',
                'space-09': '64px',
                'space-10': '80px',
                'space-11': '96px',
                'space-12': '160px',
            },
            fontSize: {
                xs: ['1.2rem', '1.6rem'],
                sm: ['1.4rem', '2.0rem'],
                base: '1.6rem',
                lg: ['1.8rem', '2.8rem'],
                xl: ['2.0rem', '2.8rem'],
                '2xl': ['2.4rem', '3.2rem'],
                '3xl': ['3.0rem', '3.6rem'],
                '4xl': ['3.6rem', '4rem'],
                'caption-01': ['1.2rem', '1.6rem'],
                'caption-02': ['1rem', '1.4rem'],
                'body-01': ['1.4rem', '2rem'],
                'body-02': ['1.6rem', '2.4rem'],
                'subtitle-01': ['1.6rem', { lineHeight: '2.4rem', fontWeight: '600' }],
                'subtitle-02': ['2rem', '2.8rem'],
            },
            boxShadow: {
                xsm: '0px 10px 16px 0px rgba(38, 36, 36, 0.04), 0px 1px 0px 0px rgba(5, 6, 12, 0.02), 0px 0px 8px 0px rgba(5, 6, 12, 0.02)',
                sharp: '0px 1px 4px 0px rgba(169, 169, 169, 0.25);',
                hover: '0px 3px 12px 0px rgba(169, 169, 169, 0.50);',
                '01': '0px 10px 16px 0px rgba(38, 36, 36, 0.04), 0px 1px 0px 0px rgba(5, 6, 12, 0.02), 0px 0px 8px 0px rgba(5, 6, 12, 0.02)',
                '03': '0px 10px 16px 0px rgba(38, 36, 36, 0.04), 0px 1px 0px 0px rgba(5, 6, 12, 0.02), 0px 0px 8px 0px rgba(5, 6, 12, 0.02)',
                'surface-01': '0px 0px 8px 0px rgba(0,0,0,0.10)',
                'card-shadow': '0px 0px 2px -1px rgba(0,0,0,0.10), 0px 1px 3px 0px rgba(0,0,0,0.10)',
                'card-hover-02': '0px 0px 8px 0px rgba(0, 0, 0, 0.12), 0px 1px 3px 0px rgba(0, 0, 0, 0.10)',
            },
            fontFamily: {
                IBMPlexSans: ['IBM Plex Sans Arabic', 'ui-sans-serif', 'system-ui'],
            },
        },
    },
    plugins: [
        require('tailwindcss-animate'),
        require('@tailwindcss/typography'),
        require('tailwind-scrollbar'),
        plugin(function ({ addBase }) {
            addBase({
                html: { fontSize: '10px' },
            })
        }),
    ],
}
